spatie/laravel-schedule-monitor

README.md
The current line `composer require ohdearapp/ohdear-php-sdk:v3` forces installation of v3.0.0 which is not compatible with Guzzle7 (and therefore not with Laravel 8).
=> Remove forced v3.0.0 for ohdearapp/ohdear-php-sdk

.github/workflows/run-tests.yml, README.md, composer.json, src/Models/MonitoredScheduledTask.php, src/ScheduleMonitorServiceProvider.php, tests/ScheduledTaskSubscriber/ScheduledTaskSubscriberTest.php, tests/stubs/artisan
This extends #42 by testing with an actual command (`php artisan help`). I had to include the `artisan` script since Testbench doesn't have it.
=> Store output v2

src/Jobs/PingOhDearJob.php
Yesterday and today I had 5 pings failing due to a 500 Internal server error on OhDear side. 
- 30-07-2021: 19:00 (Europe/Amsterdam)
- 31-07-2021 06:00 (2x), 15:00, 21:00  (Europe/Amsterdam)
As reference the OhDear ids: sites/16574/checks/97683/cron/4337
I have just retried them via Horizon and then they get accepted. (However as I noticed it too late, OhDear has marked the cron as failed). My queuing setup on this project is very simple, so there's only 1 attempt at running the job.
To not depend on user land queue settings, it might be good to leverage the Laravel Http client's build in retry() method. I've set it to 3 retries with a 10 second delay in between, but you might be a better judge of the numbers that would work better based on how long the above described 500 errors lasted. …
=> Automatically retry ping if OhDear had downtime

config/schedule-monitor.php, src/Jobs/PingOhDearJob.php
If there's a backlog of ping-jobs, ohdear will rate limit the application. This will cause 20 second time-outs on the jobs and a blocked queue. This PR makes sure that the old backlog of ping-jobs doesn't run when it's no longer relevant.
Suggestions on how to test this are welcome
=> Add retryUntil for PingOhdearJobs

src/Support/ScheduledTasks/ScheduledTasks.php, tests/Support/ScheduledTasksTest.php
Fixed issue described in this discussion: https://github.com/spatie/laravel-schedule-monitor/discussions/49
=> Take environments property into account for scheduled tasks

src/Jobs/PingOhDearJob.php
In my Laravel application I'm using immutable dates (following this article https://dyrynda.com.au/blog/laravel-immutable-dates), so `now()` return `CarbonImmutable` and not `Carbon`.
Because of that this `retryUntil` function fails for me (https://flareapp.io/share/NPLk99om#F33), adding `toDateTime()` at the end make sure the return type is correct.
=> Make sure retryUntil is returning a DateTime

src/Models/MonitoredScheduledTaskLogItem.php
Fixes the following error:
```
Spatie\ScheduleMonitor\Models\MonitoredScheduledTaskLogItem::prunable(): Return value must be of type Illuminate\Database\Query\Builder, Illuminate\Database\Eloquent\Builder returned
```
=> Fix return type

README.md
When running `model:prune` it doesn't find the `MonitoredScheduledTaskLogItem` model, unless I put it in my models folder and extend it. It seems it's a missing feature in Laravel to have prunable models in a package (currently only looks in `app/Models`).
Passing the model directly in the command, fixes that issue until Laravel adds support for it.
=> Update readme about model pruning

composer.json, tests/Commands/ListCommandTest.php, tests/Commands/SyncCommandTest.php, tests/Commands/VerifyCommandTest.php, tests/Pest.php, tests/ScheduledTaskSubscriber/PingFailedToOhDearTest.php, tests/ScheduledTaskSubscriber/PingFinishedToOhDearTest.php, tests/ScheduledTaskSubscriber/ScheduledTaskSubscriberTest.php, tests/Support/ScheduledTasksTest.php, tests/Support/ScheduledTestFactoryTest.php, tests/Support/Tasks/LastRunFailedTest.php, tests/Support/Tasks/LastRunFinishedTooLateTest.php, tests/Traits/UsesScheduleMonitoringModelsTest.php
This pull request contains changes for migrating your test suite from PHPUnit to [Pest](https://pestphp.com/) automated by the [Pest Converter](https://laravelshift.com/phpunit-to-pest-converter).
**Before merging**, you need to:
- Checkout the `shift-61511` branch
- Review **all** of the comments below for additional changes
- Run `composer update` to install Pest with your dependencies
- Run `vendor/bin/pest` to verify the conversion
=> PHPUnit to Pest Converter

README.md
Pretty much does what it says on the tin.
Don't forget to `clear:config` on production. Because yes, I forgot :(
=> chore: add multitenancy documentation

composer.json, resources/views/components/task.blade.php
This PR removes the weird calculation and takes advantage of the `flex` and `content-repeat` classes from Termwind `v1.10` version.
Thanks
=> fix: Use `flex` and `content-repeat` on Termwind outputs.

config/schedule-monitor.php, src/Models/MonitoredScheduledTask.php, src/Support/OhDearPayload/OhDearPayloadFactory.php, src/Support/OhDearPayload/Payloads/FinishedPayload.php, src/Support/OhDearPayload/Payloads/StartingPayload.php, tests/ScheduledTaskSubscriber/PingFinishedToOhDearTest.php, tests/ScheduledTaskSubscriber/PingStartingToOhDearTest.php, tests/ScheduledTaskSubscriber/ScheduledTaskSubscriberTest.php
following https://twitter.com/freekmurze/status/1613630673281028100
I didn't test it yet with the real ohdear API but I put trust into online docs https://ohdear.app/docs/features/cron-job-monitoring
Can it work ?
=> ping oh dear when scheduled task has started

README.md
I recently had a situation where I defined a cron monitor in the OhDear UI and it was automatically deleted the next time I ran the sync command, so adding a note here to flag this for others.
=> Add note that syncing will remove other monitors

README.md
The link to the Laravel docs explaining model pruning was referencing another section. Most likely, model pruning got its own section between now and then.
=> Fix anchor in link to Laravel docs

src/ScheduleMonitorServiceProvider.php
fixes the PHP warning about the creation of dynamic properties.
Closes #93
=> fix: PHP warning about creation of dynamic properties

README.md, src/Commands/SyncCommand.php, src/ScheduleMonitorServiceProvider.php, src/Support/ScheduledTasks/ScheduledTasks.php, src/Support/ScheduledTasks/Tasks/Task.php, tests/Commands/SyncCommandTest.php
This PR introduces the ability to exclude individual tasks from Oh Dear but keep them in the database.
#101 
A new macro has been added to the scheduler event called `doNotMonitorAtOhDear`. This will cause it not to be synced to Oh Dear and will clear the ping_url attribute on it in the database.
=> Allow tasks to be monitored but not synced with oh dear

src/Support/ScheduledTasks/Tasks/Task.php
I have overwritten schedule-monitor:sync command, I need to maintain runInBackground flag in `monitored_scheduled_tasks `table for which I have added a method `runsInBackground()` in `Spatie\ScheduleMonitor\Support\ScheduledTasks\Tasks\Task:class`
=> New method runsInBackground() added in  Spatie\ScheduleMonitor\Support\ScheduledTasks\Tasks\Task:class

src/Support/ScheduledTasks/Tasks/Task.php, tests/Support/Tasks/LastRunFinishedTooLateTest.php
I have also added a test case to guarantee that this edge case of 2 equal dates for last start and end date is working properly.
The main problem was that the subSecond() call on the $lastFinishedAt only makes sense when it is not the actual lastRunFinishedAt date - so i moved the subSecond() call up to the "fallback" when using the created_at date.
=> Fix wrong lastRunFinishedTooLate behaviour when lastStartedAt and lastFinishedAt are within a second because of a very fast task

src/ScheduleMonitorServiceProvider.php
When having both schedule-monitor and failed-job-monitor installed _without_ Horizon, failed-job-monitor will still regard Horizon as being installed because schedule-monitor writes to horizon config by default. Let's avoid that.
See:
https://github.com/spatie/laravel-failed-job-monitor/blob/1b4c4d3f051a1033ce6ead5433bea850bbf20878/src/Notification.php#L41
=> don't write to horizon config when not available

src/Support/ScheduledTasks/Tasks/Task.php
CronExpression::factory is deprecated since dragonmantank/cron-expression 3.0.2. This package supports Laravel 9 which uses dragonmantank/cron-expression: ^3.1 so upgrading `CronExpression::factory($this->cronExpression())` to `(new CronExpression($this->cronExpression()))` should not be an issue
=> Fix CronExpression deprecation using constructor instead of factory method

src/Support/ScheduledTasks/Tasks/Task.php
Fixes PHP 8.4 deprecation warning
This could require the release of a major version as the public API changes
=> Use explicit nullable type is Task::nextRunAt

config/schedule-monitor.php, database/factories/MonitoredScheduledTaskLogItemFactory.php, tests/Commands/SyncCommandTest.php, tests/TestClasses/FakeOhDear.php
This allows the payload to be sent to a custom URL. This can technically also be used to send the payload to different services than Oh Dear, making it more  compatible with 3rd party services.
=> Add support for a custom ping endpoint in Oh Dear

config/schedule-monitor.php, src/Commands/SyncCommand.php, src/ScheduleMonitorServiceProvider.php, tests/Commands/SyncCommandTest.php, tests/Pest.php, tests/TestClasses/FakeOhDear.php, tests/__snapshots__/SyncCommandTest__it_can_sync_the_schedule_with_the_db_and_oh_dear__1.yml, tests/__snapshots__/SyncCommandTest__it_can_use_the_keep_old_option_to_non_destructively_update_the_schedule_with_db_and_oh_dear__1.yml
This PR builds on #119 which updates the `ping_url` in tests but this doesn't trigger changes in the database when syncing.
- additional config for the Oh Dear API url to be used which defaults to the main production application
- removes the default `endpoint_url` which allows re-syncing and updating the ping_url based on either config or the returned Oh Dear scheduled task ping url (in that order)
- updated tests to use uuid as this is how we build the ping url when config url `endpoint_url` is used
=> Additional custom ping endpoint and config
